[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#00FFFF"

# Background color for the main content area.
backgroundColor = "#00FFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#00FFFF"

# Color used for almost all text.
textColor = "#00FFFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "monospace"
